// Scripture text: Berean Standard Bible (BSB), free to use.
// Passages vary naturally between one, two, and three verses.
export type Verse = { ref: string; text: string };

export const VERSES: Verse[] = [
  { ref: "Genesis 28:15", text: "Look, I am with you, and I will watch over you wherever you go, and I will bring you back to this land. For I will not leave you until I have done what I have promised you." },
  { ref: "Exodus 14:14", text: "The LORD will fight for you; you need only to be still." },
  { ref: "Deuteronomy 31:6", text: "Be strong and courageous; do not be afraid or terrified of them, for it is the LORD your God who goes with you; He will never leave you nor forsake you." },
  { ref: "Joshua 1:8-9", text: "This Book of the Law must not depart from your mouth; meditate on it day and night, so that you may be careful to do everything written in it. For then you will prosper and succeed in all you do. Have I not commanded you to be strong and courageous? Do not be afraid; do not be discouraged, for the LORD your God is with you wherever you go." },
  { ref: "1 Samuel 16:7", text: "Man does not see as God sees. For man sees the outward appearance, but the LORD sees the heart." },
  { ref: "2 Chronicles 16:9", text: "For the eyes of the LORD roam to and fro over all the earth, to show Himself strong on behalf of those whose hearts are fully devoted to Him." },
  { ref: "Nehemiah 8:10", text: "Do not grieve, for the joy of the LORD is your strength." },
  { ref: "Job 23:10", text: "Yet He knows the way I have taken; when He has tested me, I will come forth as gold." },
  { ref: "Psalm 1:2-3", text: "But his delight is in the Law of the LORD, and on His law he meditates day and night. He is like a tree planted by streams of water, yielding its fruit in season, whose leaf does not wither, and who prospers in all he does." },
  { ref: "Psalm 16:8", text: "I have set the LORD always before me. Because He is at my right hand, I will not be shaken." },
  { ref: "Psalm 16:11", text: "You have made known to me the path of life; You will fill me with joy in Your presence, with eternal pleasures at Your right hand." },
  { ref: "Psalm 19:14", text: "May the words of my mouth and the meditation of my heart be pleasing in Your sight, O LORD, my Rock and my Redeemer." },
  { ref: "Psalm 23:1-3", text: "The LORD is my shepherd; I shall not want. He makes me lie down in green pastures; He leads me beside quiet waters. He restores my soul; He guides me in the paths of righteousness for the sake of His name." },
  { ref: "Psalm 25:4-5", text: "Show me Your ways, O LORD; teach me Your paths. Guide me in Your truth and teach me, for You are the God of my salvation; all day long I wait for You." },
  { ref: "Psalm 27:1", text: "The LORD is my light and my salvation—whom shall I fear? The LORD is the stronghold of my life—whom shall I dread?" },
  { ref: "Psalm 27:14", text: "Wait patiently for the LORD; be strong and courageous. Wait patiently for the LORD!" },
  { ref: "Psalm 32:8", text: "I will instruct you and teach you the way you should go; I will give you counsel and watch over you." },
  { ref: "Psalm 34:18", text: "The LORD is near to the brokenhearted; He saves the contrite in spirit." },
  { ref: "Psalm 37:23-24", text: "The steps of a man are ordered by the LORD who delights in his way. Though he may stumble, he will not fall, for the LORD is holding his hand." },
  { ref: "Psalm 42:11", text: "Why are you downcast, O my soul? Why the unease within me? Put your hope in God, for I will yet praise Him, my Savior and my God." },
  { ref: "Psalm 46:10", text: "Be still and know that I am God; I will be exalted among the nations, I will be exalted over the earth." },
  { ref: "Psalm 51:10-12", text: "Create in me a clean heart, O God, and renew a right spirit within me. Do not cast me away from Your presence or take Your Holy Spirit from me. Restore to me the joy of Your salvation, and sustain me with a willing spirit." },
  { ref: "Psalm 55:22", text: "Cast your burden upon the LORD and He will sustain you; He will never let the righteous be shaken." },
  { ref: "Psalm 62:1-2", text: "In God alone my soul finds rest; my salvation comes from Him. He alone is my rock and my salvation; He is my fortress; I will never be shaken." },
  { ref: "Psalm 63:1", text: "O God, You are my God. Earnestly I seek You; my soul thirsts for You; my body yearns for You in a dry and weary land without water." },
  { ref: "Psalm 73:26", text: "My flesh and my heart may fail, but God is the strength of my heart and my portion forever." },
  { ref: "Psalm 84:11", text: "For the LORD God is a sun and a shield; the LORD gives grace and glory; He withholds no good thing from those who walk with integrity." },
  { ref: "Psalm 86:11", text: "Teach me Your way, O LORD, that I may walk in Your truth. Give me an undivided heart, that I may fear Your name." },
  { ref: "Psalm 91:1-2", text: "He who dwells in the shelter of the Most High will abide in the shadow of the Almighty. I will say of the LORD, \u201cHe is my refuge and my fortress, my God, in whom I trust.\u201d" },
  { ref: "Psalm 103:2-4", text: "Bless the LORD, O my soul, and do not forget all His kind deeds—He who forgives all your iniquities and heals all your diseases, who redeems your life from the Pit and crowns you with loving devotion and compassion." },
  { ref: "Psalm 118:24", text: "This is the day that the LORD has made; we will rejoice and be glad in it." },
  { ref: "Psalm 119:9-11", text: "How can a young man keep his way pure? By guarding it according to Your word. With all my heart I have sought You; do not let me stray from Your commandments. I have hidden Your word in my heart that I might not sin against You." },
  { ref: "Psalm 119:105", text: "Your word is a lamp to my feet and a light to my path." },
  { ref: "Psalm 121:1-2", text: "I lift up my eyes to the hills. From where does my help come? My help comes from the LORD, the Maker of heaven and earth." },
  { ref: "Psalm 138:8", text: "The LORD will fulfill His purpose for me. Your loving devotion, O LORD, endures forever—do not abandon the works of Your hands." },
  { ref: "Psalm 139:1-3", text: "O LORD, You have searched me and known me. You know when I sit and when I rise; You understand my thoughts from afar. You search out my path and my lying down; You are aware of all my ways." },
  { ref: "Psalm 139:23-24", text: "Search me, O God, and know my heart; test me and know my concerns. See if there is any offensive way in me; lead me in the way everlasting." },
  { ref: "Psalm 143:8", text: "Let me hear Your loving devotion in the morning, for I have put my trust in You. Teach me the way I should walk, for to You I lift up my soul." },
  { ref: "Psalm 145:18", text: "The LORD is near to all who call on Him, to all who call out to Him in truth." },
  { ref: "Proverbs 3:5-6", text: "Trust in the LORD with all your heart, and lean not on your own understanding; in all your ways acknowledge Him, and He will make your paths straight." },
  { ref: "Proverbs 4:23", text: "Guard your heart with all diligence, for from it flow springs of life." },
  { ref: "Proverbs 4:25-27", text: "Let your eyes look forward; fix your gaze straight ahead. Make a level path for your feet, and all your ways will be established. Do not swerve to the right or to the left; turn your feet away from evil." },
  { ref: "Proverbs 11:2", text: "When pride comes, disgrace follows, but with humility comes wisdom." },
  { ref: "Proverbs 12:1", text: "Whoever loves discipline loves knowledge, but he who hates correction is stupid." },
  { ref: "Proverbs 13:20", text: "He who walks with the wise will become wise, but the companion of fools will be destroyed." },
  { ref: "Proverbs 15:1", text: "A gentle answer turns away wrath, but a harsh word stirs up anger." },
  { ref: "Proverbs 16:3", text: "Commit your works to the LORD and your plans will be achieved." },
  { ref: "Proverbs 16:9", text: "A man's heart plans his course, but the LORD determines his steps." },
  { ref: "Proverbs 16:32", text: "He who is slow to anger is better than a warrior, and he who controls his temper is greater than one who captures a city." },
  { ref: "Proverbs 18:10", text: "The name of the LORD is a strong tower; the righteous run to it and are safe." },
  { ref: "Proverbs 19:21", text: "Many plans are in a man's heart, but the purpose of the LORD will prevail." },
  { ref: "Proverbs 24:16", text: "For though a righteous man may fall seven times, he still gets up; but the wicked stumble in bad times." },
  { ref: "Proverbs 27:17", text: "As iron sharpens iron, so one man sharpens another." },
  { ref: "Proverbs 28:13", text: "He who conceals his sins will not prosper, but whoever confesses and renounces them will find mercy." },
  { ref: "Ecclesiastes 3:11", text: "He has made everything beautiful in its time. He has also set eternity in the hearts of men, yet they cannot fathom the work God has done from beginning to end." },
  { ref: "Isaiah 26:3", text: "You will keep in perfect peace the steadfast of mind, because he trusts in You." },
  { ref: "Isaiah 30:15", text: "In repentance and rest is your salvation; in quietness and trust is your strength." },
  { ref: "Isaiah 40:29-31", text: "He gives strength to the weary and increases the power of the weak. Even youths grow tired and weary, and young men stumble and fall. But those who wait upon the LORD will renew their strength; they will mount up with wings like eagles; they will run and not grow weary; they will walk and not faint." },
  { ref: "Isaiah 41:10", text: "Do not fear, for I am with you; do not be afraid, for I am your God. I will strengthen you; I will surely help you; I will uphold you with My right hand of righteousness." },
  { ref: "Isaiah 43:1-2", text: "Do not fear, for I have redeemed you; I have called you by your name; you are Mine! When you pass through the waters, I will be with you; and when you go through the rivers, they will not overwhelm you." },
  { ref: "Isaiah 55:8-9", text: "For My thoughts are not your thoughts, neither are your ways My ways, declares the LORD. For as the heavens are higher than the earth, so My ways are higher than your ways and My thoughts than your thoughts." },
  { ref: "Isaiah 58:11", text: "The LORD will always guide you; He will satisfy you in a sun-scorched land and strengthen your frame. You will be like a well-watered garden, like a spring whose waters never fail." },
  { ref: "Jeremiah 17:7-8", text: "But blessed is the man who trusts in the LORD, whose confidence is in Him. He is like a tree planted by the waters that sends out its roots toward the stream." },
  { ref: "Jeremiah 29:11-13", text: "For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, to give you a future and a hope. Then you will call upon Me and come and pray to Me, and I will listen to you. You will seek Me and find Me when you search for Me with all your heart." },
  { ref: "Jeremiah 33:3", text: "Call to Me, and I will answer and show you great and unsearchable things you do not know." },
  { ref: "Lamentations 3:22-23", text: "Because of the LORD's loving devotion we are not consumed, for His compassions never fail. They are new every morning; great is Your faithfulness!" },
  { ref: "Micah 6:8", text: "He has shown you, O man, what is good. And what does the LORD require of you but to act justly, to love mercy, and to walk humbly with your God?" },
  { ref: "Habakkuk 3:17-18", text: "Though the fig tree does not bud and no fruit is on the vines, though the olive crop fails and the fields produce no food, though the sheep are cut off from the fold and no cattle are in the stalls, yet I will exult in the LORD; I will rejoice in the God of my salvation!" },
  { ref: "Zephaniah 3:17", text: "The LORD your God is among you; He is mighty to save. He will rejoice over you with gladness; He will quiet you with His love; He will rejoice over you with singing." },
  { ref: "Matthew 5:6", text: "Blessed are those who hunger and thirst for righteousness, for they will be filled." },
  { ref: "Matthew 5:14-16", text: "You are the light of the world. A city on a hill cannot be hidden. Neither do people light a lamp and put it under a basket. Instead, they set it on a stand, and it gives light to everyone in the house. In the same way, let your light shine before men, that they may see your good deeds and glorify your Father in heaven." },
  { ref: "Matthew 6:6", text: "But when you pray, go into your inner room, shut your door, and pray to your Father who is unseen. And your Father, who sees what is done in secret, will reward you." },
  { ref: "Matthew 6:33-34", text: "But seek first the kingdom of God and His righteousness, and all these things will be added unto you. Therefore do not worry about tomorrow, for tomorrow will worry about itself. Today has enough trouble of its own." },
  { ref: "Matthew 7:7-8", text: "Ask, and it will be given to you; seek, and you will find; knock, and the door will be opened to you. For everyone who asks receives; he who seeks finds; and to him who knocks, the door will be opened." },
  { ref: "Matthew 11:28-30", text: "Come to Me, all you who are weary and burdened, and I will give you rest. Take My yoke upon you and learn from Me, for I am gentle and humble in heart, and you will find rest for your souls. For My yoke is easy and My burden is light." },
  { ref: "Matthew 16:24", text: "If anyone wants to come after Me, he must deny himself and take up his cross and follow Me." },
  { ref: "Mark 1:35", text: "Early in the morning, while it was still dark, Jesus got up and slipped out to a solitary place to pray." },
  { ref: "Mark 9:24", text: "I do believe; help my unbelief!" },
  { ref: "Mark 12:30", text: "Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength." },
  { ref: "Luke 6:45", text: "The good man brings good things out of the good treasure of his heart, and the evil man brings evil things out of the evil treasure of his heart. For out of the overflow of the heart, the mouth speaks." },
  { ref: "Luke 9:23", text: "If anyone wants to come after Me, he must deny himself and take up his cross daily and follow Me." },
  { ref: "Luke 16:10", text: "Whoever is faithful with very little will also be faithful with much, and whoever is dishonest with very little will also be dishonest with much." },
  { ref: "Luke 18:1", text: "Then Jesus told them a parable about their need to pray at all times and not lose heart." },
  { ref: "John 8:31-32", text: "If you continue in My word, you are truly My disciples. Then you will know the truth, and the truth will set you free." },
  { ref: "John 10:10", text: "The thief comes only to steal and kill and destroy. I have come that they may have life, and have it in all its fullness." },
  { ref: "John 14:27", text: "Peace I leave with you; My peace I give to you. I do not give to you as the world gives. Do not let your hearts be troubled; do not be afraid." },
  { ref: "John 15:4-5", text: "Remain in Me, and I will remain in you. Just as no branch can bear fruit by itself unless it remains in the vine, neither can you bear fruit unless you remain in Me. I am the vine and you are the branches. The one who remains in Me, and I in him, will bear much fruit. For apart from Me you can do nothing." },
  { ref: "John 16:33", text: "In this world you will have tribulation. But take courage; I have overcome the world!" },
  { ref: "Acts 17:28", text: "For in Him we live and move and have our being." },
  { ref: "Acts 20:24", text: "But I consider my life of no value to me, if only I may finish my course and complete the ministry I have received from the Lord Jesus." },
  { ref: "Romans 5:3-5", text: "Not only that, but we also rejoice in our sufferings, because we know that suffering produces perseverance; perseverance, character; and character, hope. And hope does not disappoint us, because God has poured out His love into our hearts through the Holy Spirit." },
  { ref: "Romans 8:1-2", text: "Therefore there is now no condemnation for those who are in Christ Jesus, because through Christ Jesus the law of the Spirit of life set you free from the law of sin and death." },
  { ref: "Romans 8:26", text: "In the same way, the Spirit helps us in our weakness. For we do not know how we ought to pray, but the Spirit Himself intercedes for us with groans too deep for words." },
  { ref: "Romans 8:28", text: "And we know that God works all things together for the good of those who love Him, who are called according to His purpose." },
  { ref: "Romans 8:38-39", text: "For I am convinced that neither death nor life, neither angels nor principalities, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord." },
  { ref: "Romans 12:1-2", text: "Therefore I urge you, brothers, on account of God's mercy, to offer your bodies as living sacrifices, holy and pleasing to God, which is your spiritual service of worship. Do not be conformed to this world, but be transformed by the renewing of your mind." },
  { ref: "Romans 12:12", text: "Be joyful in hope, patient in affliction, faithful in prayer." },
  { ref: "Romans 15:13", text: "Now may the God of hope fill you with all joy and peace as you believe in Him, so that you may overflow with hope by the power of the Holy Spirit." },
  { ref: "1 Corinthians 6:19-20", text: "Do you not know that your body is a temple of the Holy Spirit who is in you, whom you have received from God? You are not your own; you were bought at a price. Therefore glorify God with your body." },
  { ref: "1 Corinthians 9:24-25", text: "Do you not know that in a race all the runners run, but only one receives the prize? Run in such a way as to take the prize. Everyone who competes in the games trains with strict discipline." },
  { ref: "1 Corinthians 10:13", text: "No temptation has seized you except what is common to man. And God is faithful; He will not let you be tempted beyond what you can bear. But when you are tempted, He will also provide an escape, so that you can stand up under it." },
  { ref: "1 Corinthians 15:58", text: "Therefore, my beloved brothers, be steadfast and immovable. Always excel in the work of the Lord, because you know that your labor in the Lord is not in vain." },
  { ref: "2 Corinthians 3:18", text: "And we, who with unveiled faces all reflect the glory of the Lord, are being transformed into His image with intensifying glory, which comes from the Lord, who is the Spirit." },
  { ref: "2 Corinthians 4:16-18", text: "Therefore we do not lose heart. Though our outer self is wasting away, yet our inner self is being renewed day by day. For our light and momentary affliction is producing for us an eternal weight of glory far beyond comparison. So we fix our eyes not on what is seen, but on what is unseen." },
  { ref: "2 Corinthians 5:17", text: "Therefore if anyone is in Christ, he is a new creation. The old has passed away. Behold, the new has come!" },
  { ref: "2 Corinthians 9:8", text: "And God is able to make all grace abound to you, so that in all things, at all times, having all that you need, you will abound in every good work." },
  { ref: "2 Corinthians 10:5", text: "We tear down arguments and every presumption set up against the knowledge of God; and we take captive every thought to make it obedient to Christ." },
  { ref: "2 Corinthians 12:9", text: "My grace is sufficient for you, for My power is perfected in weakness." },
  { ref: "Galatians 2:20", text: "I have been crucified with Christ, and I no longer live, but Christ lives in me. The life I live in the body, I live by faith in the Son of God, who loved me and gave Himself up for me." },
  { ref: "Galatians 5:22-23", text: "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control. Against such things there is no law." },
  { ref: "Galatians 6:9", text: "Let us not grow weary in well-doing, for in due time we will reap a harvest if we do not give up." },
  { ref: "Ephesians 2:8-10", text: "For it is by grace you have been saved through faith, and this not from yourselves; it is the gift of God, not by works, so that no one can boast. For we are God's workmanship, created in Christ Jesus to do good works, which God prepared in advance as our way of life." },
  { ref: "Ephesians 3:16-17", text: "I ask that out of the riches of His glory He may strengthen you with power through His Spirit in your inner being, so that Christ may dwell in your hearts through faith." },
  { ref: "Ephesians 4:22-24", text: "To put off your former way of life, your old self, which is being corrupted by its deceitful desires; to be renewed in the spirit of your minds; and to put on the new self, created to be like God in true righteousness and holiness." },
  { ref: "Ephesians 4:29", text: "Let no unwholesome talk come out of your mouths, but only what is helpful for building up the one in need and bringing grace to those who listen." },
  { ref: "Ephesians 6:10-11", text: "Finally, be strong in the Lord and in His mighty power. Put on the full armor of God, so that you can make your stand against the devil's schemes." },
  { ref: "Philippians 1:6", text: "Being confident of this, that He who began a good work in you will carry it on to completion until the day of Christ Jesus." },
  { ref: "Philippians 2:3-4", text: "Do nothing out of selfish ambition or empty pride, but in humility consider others more important than yourselves. Each of you should look not only to your own interests, but also to the interests of others." },
  { ref: "Philippians 3:13-14", text: "Brothers, I do not consider myself yet to have taken hold of it. But one thing I do: Forgetting what is behind and straining toward what is ahead, I press on toward the goal to win the prize of God's heavenly calling in Christ Jesus." },
  { ref: "Philippians 4:6-7", text: "Be anxious for nothing, but in everything, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus." },
  { ref: "Philippians 4:8", text: "Finally, brothers, whatever is true, whatever is honorable, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think on these things." },
  { ref: "Philippians 4:11-13", text: "I have learned to be content regardless of my circumstances. I know how to live humbly, and I know how to abound. I am accustomed to any and every situation—to being filled and being hungry, to having plenty and having need. I can do all things through Christ who gives me strength." },
  { ref: "Colossians 3:1-2", text: "Therefore, since you have been raised with Christ, strive for the things above, where Christ is seated at the right hand of God. Set your minds on things above, not on earthly things." },
  { ref: "Colossians 3:12-13", text: "Therefore, as the elect of God, holy and beloved, clothe yourselves with hearts of compassion, kindness, humility, gentleness, and patience. Bear with one another and forgive any complaint you may have against someone else. Forgive as the Lord forgave you." },
  { ref: "Colossians 3:23-24", text: "Whatever you do, work at it with your whole being, for the Lord and not for men, because you know that you will receive an inheritance from the Lord as your reward. It is the Lord Christ you are serving." },
  { ref: "1 Thessalonians 5:16-18", text: "Rejoice at all times. Pray without ceasing. Give thanks in every circumstance, for this is God's will for you in Christ Jesus." },
  { ref: "2 Thessalonians 3:3", text: "But the Lord is faithful, and He will strengthen you and guard you from the evil one." },
  { ref: "1 Timothy 4:7-8", text: "Train yourself for godliness. For physical exercise is of limited value, but godliness is valuable in every way, holding promise for the present life and for the one to come." },
  { ref: "1 Timothy 6:6-8", text: "Of course, godliness with contentment is great gain. For we brought nothing into the world, so we cannot carry anything out of it. But if we have food and clothing, we will be content with these." },
  { ref: "2 Timothy 1:7", text: "For God has not given us a spirit of fear, but of power, love, and self-control." },
  { ref: "2 Timothy 2:15", text: "Make every effort to present yourself approved to God, an unashamed workman who accurately handles the word of truth." },
  { ref: "2 Timothy 3:16-17", text: "All Scripture is God-breathed and is useful for instruction, for conviction, for correction, and for training in righteousness, so that the man of God may be complete, fully equipped for every good work." },
  { ref: "Hebrews 4:12", text: "For the word of God is living and active. Sharper than any double-edged sword, it pierces even to dividing soul and spirit, joints and marrow. It judges the thoughts and intentions of the heart." },
  { ref: "Hebrews 4:16", text: "Let us then approach the throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need." },
  { ref: "Hebrews 10:23-25", text: "Let us hold resolutely to the hope we profess, for He who promised is faithful. And let us consider how to spur one another on to love and good deeds. Let us not neglect meeting together, as some have made a habit, but let us encourage one another." },
  { ref: "Hebrews 11:1", text: "Now faith is the assurance of what we hope for and the certainty of what we do not see." },
  { ref: "Hebrews 12:1-2", text: "Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders us and the sin that so easily entangles, and let us run with endurance the race set out for us. Let us fix our eyes on Jesus, the author and perfecter of our faith." },
  { ref: "Hebrews 12:11", text: "No discipline seems enjoyable at the time, but painful. Later on, however, it yields a peaceful harvest of righteousness to those who have been trained by it." },
  { ref: "Hebrews 13:5-6", text: "Keep your lives free from the love of money and be content with what you have, for God has said: \u201cNever will I leave you, never will I forsake you.\u201d So we say with confidence: \u201cThe Lord is my helper; I will not be afraid.\u201d" },
  { ref: "James 1:2-4", text: "Consider it pure joy, my brothers, when you encounter trials of many kinds, because you know that the testing of your faith develops perseverance. Allow perseverance to finish its work, so that you may be mature and complete, not lacking anything." },
  { ref: "James 1:5", text: "Now if any of you lacks wisdom, he should ask God, who gives generously to all without finding fault, and it will be given to him." },
  { ref: "James 1:19-20", text: "My beloved brothers, understand this: Everyone should be quick to listen, slow to speak, and slow to anger, for man's anger does not bring about the righteousness that God desires." },
  { ref: "James 1:22", text: "Be doers of the word, and not hearers only. Otherwise, you are deceiving yourselves." },
  { ref: "James 4:6-8", text: "But He gives us more grace. This is why it says: \u201cGod opposes the proud, but gives grace to the humble.\u201d Submit yourselves, then, to God. Resist the devil, and he will flee from you. Draw near to God, and He will draw near to you." },
  { ref: "1 Peter 1:6-7", text: "In this you greatly rejoice, though now for a little while you may have had to suffer grief in various trials, so that the proven character of your faith—more precious than gold, which perishes even though refined by fire—may result in praise, glory, and honor." },
  { ref: "1 Peter 2:9", text: "But you are a chosen people, a royal priesthood, a holy nation, a people for God's own possession, that you may proclaim the virtues of Him who called you out of darkness into His marvelous light." },
  { ref: "1 Peter 5:6-7", text: "Humble yourselves, therefore, under God's mighty hand, that He may exalt you at the proper time. Cast all your anxiety on Him, because He cares for you." },
  { ref: "1 Peter 5:8-10", text: "Be sober-minded and alert. Your adversary the devil prowls around like a roaring lion, seeking someone to devour. Resist him, standing firm in your faith. And after you have suffered a little while, the God of all grace, who has called you to His eternal glory in Christ, will Himself restore you, secure you, strengthen you, and establish you." },
  { ref: "2 Peter 1:5-7", text: "For this very reason, make every effort to add to your faith virtue; and to virtue, knowledge; and to knowledge, self-control; and to self-control, perseverance; and to perseverance, godliness; and to godliness, brotherly kindness; and to brotherly kindness, love." },
  { ref: "2 Peter 3:18", text: "But grow in the grace and knowledge of our Lord and Savior Jesus Christ." },
  { ref: "1 John 1:9", text: "If we confess our sins, He is faithful and just to forgive us our sins and to cleanse us from all unrighteousness." },
  { ref: "1 John 3:1", text: "Behold what manner of love the Father has given us, that we should be called children of God! And that is what we are!" },
  { ref: "1 John 4:18-19", text: "There is no fear in love, but perfect love drives out fear, because fear involves punishment. The one who fears has not been perfected in love. We love because He first loved us." },
  { ref: "1 John 5:14-15", text: "And this is the confidence that we have before Him: that if we ask anything according to His will, He hears us. And if we know that He hears us in whatever we ask, we know that we already possess what we have asked of Him." },
  { ref: "Jude 1:20-21", text: "But you, beloved, by building yourselves up in your most holy faith and praying in the Holy Spirit, keep yourselves in the love of God as you await the mercy of our Lord Jesus Christ to bring you eternal life." },
  { ref: "Revelation 3:20", text: "Behold, I stand at the door and knock. If anyone hears My voice and opens the door, I will come in and dine with him, and he with Me." },
  { ref: "Revelation 21:5", text: "And the One seated on the throne said, \u201cBehold, I make all things new.\u201d" },
];
