// Public-domain scripture text (World English Bible).
export type Verse = { ref: string; text: string };

export const VERSES: Verse[] = [
  { ref: "Genesis 2:24", text: "Therefore a man will leave his father and his mother, and will join with his wife, and they will be one flesh." },
  { ref: "Genesis 2:18", text: "Yahweh God said, \u201cIt is not good that the man should be alone; I will make him a helper comparable to him.\u201d" },
  { ref: "Ruth 1:16", text: "Where you go, I will go; and where you stay, I will stay. Your people shall be my people, and your God my God." },
  { ref: "Joshua 24:15", text: "As for me and my house, we will serve Yahweh." },
  { ref: "Psalm 23:1", text: "Yahweh is my shepherd; I shall lack nothing." },
  { ref: "Psalm 20:4", text: "May he grant you your heart\u2019s desire, and fulfill all your counsel." },
  { ref: "Psalm 37:4", text: "Also delight yourself in Yahweh, and he will give you the desires of your heart." },
  { ref: "Psalm 37:5", text: "Commit your way to Yahweh. Trust in him, and he will do it." },
  { ref: "Psalm 90:12", text: "So teach us to count our days, that we may gain a heart of wisdom." },
  { ref: "Psalm 127:1", text: "Unless Yahweh builds the house, they who build it labor in vain." },
  { ref: "Psalm 133:1", text: "See how good and how pleasant it is for brothers to live together in unity!" },
  { ref: "Psalm 143:8", text: "Cause me to hear your loving kindness in the morning, for I trust in you. Cause me to know the way in which I should walk." },
  { ref: "Psalm 46:1", text: "God is our refuge and strength, a very present help in trouble." },
  { ref: "Psalm 34:8", text: "Oh taste and see that Yahweh is good. Blessed is the man who takes refuge in him." },
  { ref: "Psalm 118:24", text: "This is the day that Yahweh has made. We will rejoice and be glad in it." },
  { ref: "Psalm 139:23-24", text: "Search me, God, and know my heart. Try me, and know my thoughts. See if there is any wicked way in me, and lead me in the everlasting way." },
  { ref: "Proverbs 3:5-6", text: "Trust in Yahweh with all your heart, and don\u2019t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight." },
  { ref: "Proverbs 3:9-10", text: "Honor Yahweh with your substance, with the first fruits of all your increase; so your barns will be filled with plenty." },
  { ref: "Proverbs 13:11", text: "Wealth gained dishonestly dwindles away, but he who gathers by hand makes it grow." },
  { ref: "Proverbs 21:5", text: "The plans of the diligent surely lead to profit; and everyone who is hasty surely rushes to poverty." },
  { ref: "Proverbs 21:20", text: "There is precious treasure and oil in the dwelling of the wise, but a foolish man swallows it up." },
  { ref: "Proverbs 22:7", text: "The rich rule over the poor. The borrower is servant to the lender." },
  { ref: "Proverbs 24:3-4", text: "Through wisdom a house is built; by understanding it is established; by knowledge the rooms are filled with all rare and beautiful treasure." },
  { ref: "Proverbs 27:17", text: "Iron sharpens iron; so a man sharpens his friend\u2019s countenance." },
  { ref: "Proverbs 15:1", text: "A gentle answer turns away wrath, but a harsh word stirs up anger." },
  { ref: "Proverbs 16:3", text: "Commit your deeds to Yahweh, and your plans shall succeed." },
  { ref: "Proverbs 16:9", text: "A man\u2019s heart plans his course, but Yahweh directs his steps." },
  { ref: "Proverbs 17:17", text: "A friend loves at all times; and a brother is born for adversity." },
  { ref: "Proverbs 18:22", text: "Whoever finds a wife finds a good thing, and obtains favor of Yahweh." },
  { ref: "Proverbs 19:21", text: "There are many plans in a man\u2019s heart, but Yahweh\u2019s counsel will prevail." },
  { ref: "Proverbs 31:11", text: "The heart of her husband trusts in her. He shall have no lack of gain." },
  { ref: "Proverbs 11:14", text: "Where there is no wise guidance, the nation falls, but in the multitude of counselors there is victory." },
  { ref: "Proverbs 12:15", text: "The way of a fool is right in his own eyes, but he who is wise listens to counsel." },
  { ref: "Proverbs 28:20", text: "A faithful man is rich with blessings; but one who is eager to be rich will not go unpunished." },
  { ref: "Proverbs 30:8", text: "Give me neither poverty nor riches. Feed me with the food that is needful for me." },
  { ref: "Ecclesiastes 3:1", text: "For everything there is a season, and a time for every purpose under heaven." },
  { ref: "Ecclesiastes 4:9-10", text: "Two are better than one, because they have a good reward for their labor. For if they fall, the one will lift up his fellow." },
  { ref: "Ecclesiastes 4:12", text: "A threefold cord is not quickly broken." },
  { ref: "Ecclesiastes 5:10", text: "He who loves silver shall not be satisfied with silver, nor he who loves abundance, with increase." },
  { ref: "Song of Solomon 8:7", text: "Many waters can\u2019t quench love, neither can floods drown it." },
  { ref: "Isaiah 26:3", text: "You will keep whoever\u2019s mind is steadfast in perfect peace, because he trusts in you." },
  { ref: "Isaiah 40:31", text: "But those who wait for Yahweh will renew their strength. They will mount up with wings like eagles." },
  { ref: "Isaiah 41:10", text: "Don\u2019t be afraid, for I am with you. Don\u2019t be dismayed, for I am your God. I will strengthen you." },
  { ref: "Isaiah 43:19", text: "Behold, I will do a new thing. It springs out now. Don\u2019t you know it?" },
  { ref: "Jeremiah 17:7", text: "Blessed is the man who trusts in Yahweh, and whose confidence is in Yahweh." },
  { ref: "Jeremiah 29:11", text: "For I know the thoughts that I think toward you, says Yahweh, thoughts of peace, and not of evil, to give you hope and a future." },
  { ref: "Lamentations 3:22-23", text: "His compassions don\u2019t fail. They are new every morning. Great is your faithfulness." },
  { ref: "Micah 6:8", text: "What does Yahweh require of you, but to act justly, to love mercy, and to walk humbly with your God?" },
  { ref: "Habakkuk 2:3", text: "For the vision is yet for the appointed time. Though it takes time, wait for it." },
  { ref: "Malachi 3:10", text: "Bring the whole tithe into the storehouse, and test me now in this, says Yahweh of Armies." },
  { ref: "Matthew 6:19-20", text: "Don\u2019t lay up treasures for yourselves on the earth\u2026 but lay up for yourselves treasures in heaven." },
  { ref: "Matthew 6:21", text: "For where your treasure is, there your heart will be also." },
  { ref: "Matthew 6:24", text: "No one can serve two masters\u2026 You can\u2019t serve both God and Mammon." },
  { ref: "Matthew 6:33", text: "But seek first God\u2019s Kingdom and his righteousness; and all these things will be given to you as well." },
  { ref: "Matthew 6:34", text: "Therefore don\u2019t be anxious for tomorrow, for tomorrow will be anxious for itself." },
  { ref: "Matthew 7:24", text: "Everyone therefore who hears these words of mine and does them, I will liken him to a wise man who built his house on a rock." },
  { ref: "Matthew 11:28", text: "Come to me, all you who labor and are heavily burdened, and I will give you rest." },
  { ref: "Matthew 19:6", text: "So that they are no more two, but one flesh. What therefore God has joined together, don\u2019t let man tear apart." },
  { ref: "Matthew 22:37-39", text: "You shall love the Lord your God with all your heart\u2026 You shall love your neighbor as yourself." },
  { ref: "Matthew 25:21", text: "Well done, good and faithful servant. You have been faithful over a few things, I will set you over many things." },
  { ref: "Mark 10:9", text: "What therefore God has joined together, let no man separate." },
  { ref: "Luke 6:38", text: "Give, and it will be given to you: good measure, pressed down, shaken together, and running over." },
  { ref: "Luke 12:15", text: "Beware! Keep yourselves from covetousness, for a man\u2019s life doesn\u2019t consist of the abundance of the things which he possesses." },
  { ref: "Luke 14:28", text: "For which of you, desiring to build a tower, doesn\u2019t first sit down and count the cost, to see if he has enough to complete it?" },
  { ref: "Luke 16:10", text: "He who is faithful in a very little is faithful also in much." },
  { ref: "John 13:34", text: "A new commandment I give to you, that you love one another. Just as I have loved you, you also love one another." },
  { ref: "John 14:27", text: "Peace I leave with you. My peace I give to you\u2026 Don\u2019t let your heart be troubled." },
  { ref: "John 15:5", text: "I am the vine. You are the branches\u2026 for apart from me you can do nothing." },
  { ref: "John 15:12", text: "This is my commandment, that you love one another, even as I have loved you." },
  { ref: "Romans 5:3-4", text: "Suffering produces perseverance; and perseverance, proven character; and proven character, hope." },
  { ref: "Romans 8:28", text: "We know that all things work together for good for those who love God." },
  { ref: "Romans 12:10", text: "In love of the brothers be tenderly affectionate to one another; in honor preferring one another." },
  { ref: "Romans 12:12", text: "Rejoicing in hope; enduring in troubles; continuing steadfastly in prayer." },
  { ref: "Romans 13:8", text: "Owe no one anything, except to love one another; for he who loves his neighbor has fulfilled the law." },
  { ref: "Romans 15:5", text: "May the God of perseverance and of encouragement grant you to be of the same mind with one another." },
  { ref: "Romans 15:13", text: "Now may the God of hope fill you with all joy and peace in believing." },
  { ref: "1 Corinthians 10:31", text: "Whether therefore you eat, or drink, or whatever you do, do all to the glory of God." },
  { ref: "1 Corinthians 13:4-5", text: "Love is patient and is kind\u2026 doesn\u2019t seek its own way, is not provoked, takes no account of evil." },
  { ref: "1 Corinthians 13:7", text: "Love bears all things, believes all things, hopes all things, endures all things." },
  { ref: "1 Corinthians 16:14", text: "Let all that you do be done in love." },
  { ref: "2 Corinthians 9:7", text: "Let each man give according as he has determined in his heart\u2026 for God loves a cheerful giver." },
  { ref: "2 Corinthians 9:8", text: "And God is able to make all grace abound to you, that you, always having all sufficiency in everything, may abound to every good work." },
  { ref: "Galatians 5:22-23", text: "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith, gentleness, and self-control." },
  { ref: "Galatians 6:9", text: "Let\u2019s not be weary in doing good, for we will reap in due season, if we don\u2019t give up." },
  { ref: "Ephesians 4:2-3", text: "With all lowliness and humility, with patience, bearing with one another in love; being eager to keep the unity of the Spirit." },
  { ref: "Ephesians 4:29", text: "Let no corrupt speech proceed out of your mouth, but only what is good for building others up." },
  { ref: "Ephesians 4:32", text: "And be kind to one another, tender hearted, forgiving each other, just as God also in Christ forgave you." },
  { ref: "Ephesians 5:25", text: "Husbands, love your wives, even as Christ also loved the assembly and gave himself up for it." },
  { ref: "Ephesians 5:33", text: "Nevertheless each of you must also love his own wife even as himself; and let the wife see that she respects her husband." },
  { ref: "Philippians 2:3-4", text: "Doing nothing through rivalry or through conceit, but in humility, each counting others better than himself." },
  { ref: "Philippians 4:6-7", text: "In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God." },
  { ref: "Philippians 4:11-12", text: "For I have learned in whatever state I am, to be content\u2026 I have learned the secret both to be filled and to be hungry." },
  { ref: "Philippians 4:19", text: "My God will supply every need of yours according to his riches in glory in Christ Jesus." },
  { ref: "Colossians 3:12", text: "Put on therefore, as God\u2019s chosen ones, a heart of compassion, kindness, lowliness, humility, and perseverance." },
  { ref: "Colossians 3:14", text: "Above all these things, walk in love, which is the bond of perfection." },
  { ref: "Colossians 3:23", text: "And whatever you do, work heartily, as for the Lord, and not for men." },
  { ref: "1 Thessalonians 5:11", text: "Therefore exhort one another, and build each other up, even as you also do." },
  { ref: "1 Thessalonians 5:16-18", text: "Always rejoice. Pray without ceasing. In everything give thanks, for this is the will of God." },
  { ref: "1 Timothy 6:6", text: "But godliness with contentment is great gain." },
  { ref: "1 Timothy 6:17-18", text: "Charge those who are rich in this present world that they not be arrogant, nor have their hope set on the uncertainty of riches." },
  { ref: "Hebrews 10:24", text: "Let us consider how to provoke one another to love and good works." },
  { ref: "Hebrews 11:1", text: "Now faith is assurance of things hoped for, proof of things not seen." },
  { ref: "Hebrews 13:5", text: "Be free from the love of money, content with such things as you have, for he has said, \u201cI will in no way leave you.\u201d" },
  { ref: "James 1:5", text: "But if any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach." },
  { ref: "James 1:17", text: "Every good gift and every perfect gift is from above, coming down from the Father of lights." },
  { ref: "James 1:19", text: "Let every man be swift to hear, slow to speak, and slow to anger." },
  { ref: "James 4:13-15", text: "You ought to say, \u201cIf the Lord wills, we will both live, and do this or that.\u201d" },
  { ref: "1 Peter 3:7", text: "You husbands, in the same way, live with your wives according to knowledge, giving honor to the woman." },
  { ref: "1 Peter 4:8", text: "And above all things be earnest in your love among yourselves, for love covers a multitude of sins." },
  { ref: "1 Peter 5:7", text: "Casting all your worries on him, because he cares for you." },
  { ref: "1 John 3:18", text: "My little children, let\u2019s not love in word only, or with the tongue only, but in deed and truth." },
  { ref: "1 John 4:19", text: "We love him, because he first loved us." },
  { ref: "3 John 1:2", text: "Beloved, I pray that you may prosper in all things and be healthy, even as your soul prospers." },
];
