/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestdevRouteImport } from './routes/questdev'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AssistantIndexRouteImport } from './routes/assistant.index'
import { Route as AssistantThreadIdRouteImport } from './routes/assistant.$threadId'
import { Route as ApiPublicHealthSnapRouteImport } from './routes/api/public/health-snap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestdevRoute = QuestdevRouteImport.update({
  id: '/questdev',
  path: '/questdev',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantThreadIdRoute = AssistantThreadIdRouteImport.update({
  id: '/assistant/$threadId',
  path: '/assistant/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthSnapRoute = ApiPublicHealthSnapRouteImport.update({
  id: '/api/public/health-snap',
  path: '/api/public/health-snap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/questdev': typeof QuestdevRoute
  '/unlock': typeof UnlockRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/assistant/': typeof AssistantIndexRoute
  '/api/public/health-snap': typeof ApiPublicHealthSnapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/questdev': typeof QuestdevRoute
  '/unlock': typeof UnlockRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/assistant': typeof AssistantIndexRoute
  '/api/public/health-snap': typeof ApiPublicHealthSnapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/questdev': typeof QuestdevRoute
  '/unlock': typeof UnlockRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/assistant/': typeof AssistantIndexRoute
  '/api/public/health-snap': typeof ApiPublicHealthSnapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/questdev'
    | '/unlock'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/assistant/'
    | '/api/public/health-snap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/questdev'
    | '/unlock'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/assistant'
    | '/api/public/health-snap'
  id:
    | '__root__'
    | '/'
    | '/questdev'
    | '/unlock'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/assistant/'
    | '/api/public/health-snap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuestdevRoute: typeof QuestdevRoute
  UnlockRoute: typeof UnlockRoute
  ApiChatRoute: typeof ApiChatRoute
  AssistantThreadIdRoute: typeof AssistantThreadIdRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
  ApiPublicHealthSnapRoute: typeof ApiPublicHealthSnapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questdev': {
      id: '/questdev'
      path: '/questdev'
      fullPath: '/questdev'
      preLoaderRoute: typeof QuestdevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/$threadId': {
      id: '/assistant/$threadId'
      path: '/assistant/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AssistantThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health-snap': {
      id: '/api/public/health-snap'
      path: '/api/public/health-snap'
      fullPath: '/api/public/health-snap'
      preLoaderRoute: typeof ApiPublicHealthSnapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuestdevRoute: QuestdevRoute,
  UnlockRoute: UnlockRoute,
  ApiChatRoute: ApiChatRoute,
  AssistantThreadIdRoute: AssistantThreadIdRoute,
  AssistantIndexRoute: AssistantIndexRoute,
  ApiPublicHealthSnapRoute: ApiPublicHealthSnapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
