/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as ApiPublicHealthSnapRouteImport } from './routes/api/public/health-snap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthSnapRoute = ApiPublicHealthSnapRouteImport.update({
  id: '/api/public/health-snap',
  path: '/api/public/health-snap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/api/public/health-snap': typeof ApiPublicHealthSnapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/api/public/health-snap': typeof ApiPublicHealthSnapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/api/public/health-snap': typeof ApiPublicHealthSnapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/unlock' | '/api/public/health-snap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/unlock' | '/api/public/health-snap'
  id: '__root__' | '/' | '/unlock' | '/api/public/health-snap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UnlockRoute: typeof UnlockRoute
  ApiPublicHealthSnapRoute: typeof ApiPublicHealthSnapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health-snap': {
      id: '/api/public/health-snap'
      path: '/api/public/health-snap'
      fullPath: '/api/public/health-snap'
      preLoaderRoute: typeof ApiPublicHealthSnapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UnlockRoute: UnlockRoute,
  ApiPublicHealthSnapRoute: ApiPublicHealthSnapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
